### ISSUE TITLE
Use of nodelets

### ISSUE THREAD

**Issue by MaslinuPoimal** [tum-phoenix/drive_ros_image_recognition#1]
Transporting a lot of image messages between nodes might cause issues, might be helpful to switch to [nodelets](http://wiki.ros.org/nodelet) for transport instead.

Should be easy to implement in parallel to normal nodes as it uses mostly the same interfaces. According to [this](https://books.google.de/books?id=MCO6BQAAQBAJ&pg=PA59&lpg=PA59&dq=nodelets+image+transport+ros&source=bl&ots=m9I9gacUPB&sig=eA520oouswGKBGfk0AS5ZLs1_98&hl=de&sa=X&ved=0ahUKEwjKyPyr1LfUAhWFvBoKHSQ6BYEQ6AEIfDAO#v=onepage&q=nodelets%20image%20transport%20ros&f=false) it can give a substantial FPS increase at our resolutions.

**Comment by Phibedy** [comment]
What I don't like about nodelets:
"""
Note that when publishing in this fashion, there is an implicit contract between you and roscpp: you may not modify the message you've sent after you send it, since that pointer will be passed directly to any intraprocess subscribers. If you want to send another message, you must allocate a new one and send that. 
"""
If you publish a msg as sharedPtr, will it automatically be serialized and send if it is read from a node instead of a nodelet?

**Comment by MaslinuPoimal** [comment]
> If you publish a msg as sharedPtr, will it automatically be serialized and send if it is read from a node instead of a nodelet?

Yes, it will serialize automatically between nodes. Non-const pointers will also be serialized, so we can use nodelets after preprocessing between the preprocess node and detection nodes. Will test for line detection if the OpenCV sobel & co. stuff doesn't break.

**Comment by fabolhak** [comment]
ok cool. We can discuss that on Wednesday ;)

**Comment by MaslinuPoimal** [comment]
Nodelets are used for all vision nodes as of now, so closing.
